version: '2.1'
services:
  redis:
    image: redis

  db:
    image: centos/postgresql-95-centos7
    environment:
    - POSTGRESQL_USER=pebbles
    - POSTGRESQL_PASSWORD=pebbles
    - POSTGRESQL_DATABASE=pebbles

  api:
    image: cscfi/pebbles:latest
    links:
    - db
    - redis
    depends_on:
    - db
    - redis
    ports:
    - '8080:8080'
    env_file: local.env
    environment:
    - APP_MODULE=pebbles.server:app
    - DB_AUTOMIGRATION=1
    - PB_SQLALCHEMY_DATABASE_URI=postgresql://pebbles:pebbles@db/pebbles
    - APP_CONFIG=/opt/app-root/src/deployment/gunicorn-debug.cfg
    volumes:
    # mount the source directory for local development
    - ..:/opt/app-root/src:ro

  worker:
    image: cscfi/pebbles:latest
    links:
    - redis
    - api
    env_file: local.env
    environment:
    - APP_SCRIPT=/opt/app-root/src/deployment/run_celery.bash
    - CELERY_PROCESS_NAME=worker
    - CELERY_QUEUE=provisioning_tasks-1
    - CELERY_LOGLEVEL=DEBUG
    volumes:
    # mount the source directory for local development
    - ..:/opt/app-root/src:ro

  system-worker:
    image: cscfi/pebbles:latest
    links:
    - redis
    - api
    env_file: local.env
    environment:
    - APP_SCRIPT=/opt/app-root/src/deployment/run_celery.bash
    - CELERY_PROCESS_NAME=system_worker
    - CELERY_QUEUE=system_tasks
    - CELERY_LOGLEVEL=DEBUG
    volumes:
# mount the source directory for local development
    - ..:/opt/app-root/src:ro

  periodical-worker:
    image: cscfi/pebbles:latest
    links:
    - redis
    - api
    env_file: local.env
    environment:
    - APP_SCRIPT=/opt/app-root/src/deployment/run_celery.bash
    - CELERY_CMD=beat
    - CELERY_PROCESS_NAME=system_worker
    - CELERY_QUEUE=system
    - CELERY_LOGLEVEL=DEBUG
