"""empty message

Revision ID: 098310e079e2
Revises: 9yuk6g899741
Create Date: 2019-07-17 13:28:50.035725

"""

# revision identifiers, used by Alembic.
revision = '098310e079e2'
down_revision = '9yuk6g899741'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blueprints', sa.Column('visibility', sa.Boolean(), nullable=True))
    op.create_unique_constraint(op.f('uq_users_email_id'), 'users', ['email_id'])
    op.create_unique_constraint(op.f('uq_users_eppn'), 'users', ['eppn'])
    op.drop_constraint(u'uq_users_email', 'users', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'uq_users_email', 'users', ['eppn'])
    op.drop_constraint(op.f('uq_users_eppn'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_email_id'), 'users', type_='unique')
    op.drop_column('blueprints', 'visibility')
    ### end Alembic commands ###
