"""add workspace.config

Revision ID: 2a55fb4059d4
Revises: 90ad52b47b03
Create Date: 2022-10-28 10:53:07.681816

"""
import json

# revision identifiers, used by Alembic.
revision = '2a55fb4059d4'
down_revision = '90ad52b47b03'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('config', sa.Text(), nullable=True))
    default_config = dict(scheduler_tolerations=['role=user'])
    op.execute(
        "UPDATE workspaces "
        "   SET config='" + json.dumps(default_config)+"'"
        " WHERE config is null")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'config')
    # ### end Alembic commands ###
