"""empty message

Revision ID: 2b54be9401bd
Revises: a8e0d5299a86
Create Date: 2018-07-18 11:24:54.198816

"""

# revision identifiers, used by Alembic.
revision = '2b54be9401bd'
down_revision = 'a8e0d5299a86'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('joining_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'joining_date')
    ### end Alembic commands ###
