"""add workspace memory limits

Revision ID: 33431e7c6011
Revises: e96f531e867f
Create Date: 2022-04-25 09:49:22.889812

"""

# revision identifiers, used by Alembic.
revision = '33431e7c6011'
down_revision = 'e96f531e867f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('memory_limit_gib', sa.Integer(), nullable=True))
    op.execute(
        "UPDATE workspaces SET memory_limit_gib=50 WHERE memory_limit_gib is null")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'memory_limit_gib')
    # ### end Alembic commands ###
