"""empty message

Revision ID: 36218ef15edc
Revises: c0732331a3c8
Create Date: 2016-10-13 13:53:30.935455

"""

# revision identifiers, used by Alembic.
revision = '36218ef15edc'
down_revision = 'c0732331a3c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('_join_code', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_config', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups'))
    )
    op.create_table('blueprint_templates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('plugin', sa.String(length=32), nullable=True),
    sa.Column('blueprint_schema', sa.Text(), nullable=True),
    sa.Column('blueprint_form', sa.Text(), nullable=True),
    sa.Column('blueprint_model', sa.Text(), nullable=True),
    sa.Column('allowed_attrs', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plugin'], ['plugins.id'], name=op.f('fk_blueprint_templates_plugin_plugins')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blueprint_templates'))
    )
    op.create_table('groups_banned_users',
    sa.Column('group_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_groups_banned_users_group_id_groups')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_groups_banned_users_user_id_users')),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name=op.f('pk_groups_banned_users'))
    )
    op.create_table('groups_owners',
    sa.Column('group_id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_groups_owners_group_id_groups')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_groups_owners_owner_id_users')),
    sa.PrimaryKeyConstraint('group_id', 'owner_id', name=op.f('pk_groups_owners'))
    )
    op.create_table('groups_users',
    sa.Column('group_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_groups_users_group_id_groups')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_groups_users_user_id_users')),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name=op.f('pk_groups_users'))
    )
    op.add_column(u'blueprints', sa.Column('group_id', sa.String(length=32), nullable=True))
    op.add_column(u'blueprints', sa.Column('template_id', sa.String(length=32), nullable=True))
    op.drop_constraint(u'fk_blueprints_plugin_plugins', 'blueprints', type_='foreignkey')
    op.create_foreign_key(op.f('fk_blueprints_template_id_blueprint_templates'), 'blueprints', 'blueprint_templates', ['template_id'], ['id'])
    op.create_foreign_key(op.f('fk_blueprints_group_id_groups'), 'blueprints', 'groups', ['group_id'], ['id'])
    op.drop_column(u'blueprints', 'plugin')
    op.create_unique_constraint(op.f('uq_locks_lock_id'), 'locks', ['lock_id'])
    op.add_column(u'users', sa.Column('is_group_owner', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'is_group_owner')
    op.drop_constraint(op.f('uq_locks_lock_id'), 'locks', type_='unique')
    op.add_column(u'blueprints', sa.Column('plugin', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_blueprints_group_id_groups'), 'blueprints', type_='foreignkey')
    op.drop_constraint(op.f('fk_blueprints_template_id_blueprint_templates'), 'blueprints', type_='foreignkey')
    op.create_foreign_key(u'fk_blueprints_plugin_plugins', 'blueprints', 'plugins', ['plugin'], ['id'])
    op.drop_column(u'blueprints', 'template_id')
    op.drop_column(u'blueprints', 'group_id')
    op.drop_table('groups_users')
    op.drop_table('groups_owners')
    op.drop_table('groups_banned_users')
    op.drop_table('blueprint_templates')
    op.drop_table('groups')
    ### end Alembic commands ###
