"""add_user_deletion_request

Revision ID: 3b8b86a7af77
Revises: b86c5da50575
Create Date: 2024-12-05 14:10:29.118653

"""

# revision identifiers, used by Alembic.
revision = '3b8b86a7af77'
down_revision = 'b86c5da50575'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deletion_requested_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deletion_requested_date')
    # ### end Alembic commands ###
