"""empty message

Revision ID: 5b9110dd4ffd
Revises: 902fbdab393a
Create Date: 2017-02-10 17:22:04.107017

"""

# revision identifiers, used by Alembic.
revision = '5b9110dd4ffd'
down_revision = '902fbdab393a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('instance_id', sa.String(length=32), nullable=True),
    sa.Column('log_level', sa.String(length=8), nullable=True),
    sa.Column('log_type', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_instance_logs_instance_id_instances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instance_logs'))
    )
    op.create_index(op.f('ix_instance_logs_instance_id'), 'instance_logs', ['instance_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instance_logs_instance_id'), table_name='instance_logs')
    op.drop_table('instance_logs')
    ### end Alembic commands ###
