"""empty message

Revision ID: 75e2eec39f4c
Revises: 9yuk6g899741
Create Date: 2019-09-02 13:41:06.605739

"""

# revision identifiers, used by Alembic.
revision = '75e2eec39f4c'
down_revision = '9yuk6g899741'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notebooks_enability',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('is_notebooks_enable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notebooks_enability'))
    )
    ### op.create_unique_constraint(op.f('uq_users_email_id'), 'users', ['email_id'])
    ### op.create_unique_constraint(op.f('uq_users_eppn'), 'users', ['eppn'])
    ### op.drop_constraint(u'uq_users_email', 'users', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### op.create_unique_constraint(u'uq_users_email', 'users', ['eppn'])
    ### op.drop_constraint(op.f('uq_users_eppn'), 'users', type_='unique')
    ### op.drop_constraint(op.f('uq_users_email_id'), 'users', type_='unique')
    op.drop_table('notebooks_enability')
    ### end Alembic commands ###
