"""empty message

Revision ID: 7d8f697053e9
Revises: 36218ef15edc
Create Date: 2016-10-18 12:51:14.892632

"""

# revision identifiers, used by Alembic.
revision = '7d8f697053e9'
down_revision = '36218ef15edc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups_managers',
    sa.Column('group_id', sa.String(length=32), nullable=False),
    sa.Column('manager_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_groups_managers_group_id_groups')),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('fk_groups_managers_manager_id_users')),
    sa.PrimaryKeyConstraint('group_id', 'manager_id', name=op.f('pk_groups_managers'))
    )
    op.drop_table('groups_owners')
    op.add_column('groups', sa.Column('owner_id', sa.String(length=32), nullable=True))
    op.create_foreign_key(op.f('fk_groups_owner_id_users'), 'groups', 'users', ['owner_id'], ['id'])
    op.drop_column('groups', 'user_config')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('user_config', sa.TEXT, nullable=True))
    op.drop_constraint(op.f('fk_groups_owner_id_users'), 'groups', type_='foreignkey')
    op.drop_column('groups', 'owner_id')
    op.create_table('groups_owners',
    sa.Column('group_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], [u'groups.id'], name=u'fk_groups_owners_group_id_groups'),
    sa.ForeignKeyConstraint(['owner_id'], [u'users.id'], name=u'fk_groups_owners_owner_id_users'),
    sa.PrimaryKeyConstraint('group_id', 'owner_id', name=u'pk_groups_owners')
    )
    op.drop_table('groups_managers')
    ### end Alembic commands ###
