"""empty message

Revision ID: 7fce82b6ce10
Revises: 9yuk6g899741
Create Date: 2019-08-23 11:02:56.225812

"""

# revision identifiers, used by Alembic.
revision = '7fce82b6ce10'
down_revision = '9yuk6g899741'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locks', sa.Column('id', sa.String(length=64), nullable=False))
    op.add_column('locks', sa.Column('owner', sa.String(length=64), nullable=True))
    op.create_unique_constraint(op.f('uq_locks_id'), 'locks', ['id'])
    op.drop_constraint('uq_locks_lock_id', 'locks', type_='unique')
    op.drop_column('locks', 'lock_id')
    op.create_unique_constraint(op.f('uq_users_email_id'), 'users', ['email_id'])
    op.create_unique_constraint(op.f('uq_users_eppn'), 'users', ['eppn'])
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_users_email', 'users', ['eppn'])
    op.drop_constraint(op.f('uq_users_eppn'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_email_id'), 'users', type_='unique')
    op.add_column('locks', sa.Column('lock_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_unique_constraint('uq_locks_lock_id', 'locks', ['lock_id'])
    op.drop_constraint(op.f('uq_locks_id'), 'locks', type_='unique')
    op.drop_column('locks', 'owner')
    op.drop_column('locks', 'id')
    # ### end Alembic commands ###
