"""empty message

Revision ID: 8da5bede3ed4
Revises: 545dfafaa2a8
Create Date: 2017-11-13 12:20:09.464470

"""

# revision identifiers, used by Alembic.
revision = '8da5bede3ed4'
down_revision = '545dfafaa2a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blueprints', sa.Column('current_status', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blueprints', 'current_status')
    ### end Alembic commands ###
