"""empty message

Revision ID: 902fbdab393a
Revises: d09db0106be9
Create Date: 2016-11-23 15:33:57.834197

"""

# revision identifiers, used by Alembic.
revision = '902fbdab393a'
down_revision = 'd09db0106be9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups_users_association',
    sa.Column('group_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('manager', sa.Boolean(), nullable=True),
    sa.Column('owner', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_groups_users_association_group_id_groups')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_groups_users_association_user_id_users')),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name=op.f('pk_groups_users_association'))
    )
    op.drop_table('groups_managers')
    op.drop_table('groups_users')
    op.drop_constraint(u'fk_groups_owner_id_users', 'groups', type_='foreignkey')
    op.drop_column('groups', 'owner_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('owner_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.create_foreign_key(u'fk_groups_owner_id_users', 'groups', 'users', ['owner_id'], ['id'])
    op.create_table('groups_users',
    sa.Column('group_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], [u'groups.id'], name=u'fk_groups_users_group_id_groups'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'fk_groups_users_user_id_users'),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name=u'pk_groups_users')
    )
    op.create_table('groups_managers',
    sa.Column('group_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('manager_id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], [u'groups.id'], name=u'fk_groups_managers_group_id_groups'),
    sa.ForeignKeyConstraint(['manager_id'], [u'users.id'], name=u'fk_groups_managers_manager_id_users'),
    sa.PrimaryKeyConstraint('group_id', 'manager_id', name=u'pk_groups_managers')
    )
    op.drop_table('groups_users_association')
    ### end Alembic commands ###
