"""longer workspace name

Revision ID: 90ad52b47b03
Revises: e5ec28975cca
Create Date: 2022-09-21 08:30:53.088266

"""

# revision identifiers, used by Alembic.
revision = '90ad52b47b03'
down_revision = 'e5ec28975cca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspaces', 'name',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###
