"""empty message

Revision ID: 91f5561daef2
Revises: 8da5bede3ed4
Create Date: 2017-12-12 13:14:49.115092

"""

# revision identifiers, used by Alembic.
revision = '91f5561daef2'
down_revision = '8da5bede3ed4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('keypairs', '_public_key',
               existing_type=sa.VARCHAR(length=450),
               type_=sa.String(length=1025),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('keypairs', '_public_key',
               existing_type=sa.String(length=1025),
               type_=sa.VARCHAR(length=450),
               existing_nullable=True)
    ### end Alembic commands ###
