"""add custom images

Revision ID: 947e2b4aa58f
Revises: b86c5da50575
Create Date: 2024-09-04 13:42:31.585594

"""

# revision identifiers, used by Alembic.
revision = '947e2b4aa58f'
down_revision = '3b8b86a7af77'

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'custom_images',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('workspace_id', sa.String(length=32), nullable=True),
        sa.Column('state', sa.String(length=32), nullable=True),
        sa.Column('to_be_deleted', sa.Boolean(), nullable=True),
        sa.Column('name', sa.String(length=64), nullable=True),
        sa.Column('tag', sa.String(length=64), nullable=True),
        sa.Column('definition', sa.Text(), nullable=True),
        sa.Column('dockerfile', sa.Text(), nullable=True),
        sa.Column('build_system_id', sa.String(length=64), nullable=True),
        sa.Column('build_system_output', sa.Text(), nullable=True),
        sa.Column('url', sa.String(length=256), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_images')
    # ### end Alembic commands ###
