"""empty message

Revision ID: a8e0d5299a86
Revises: 91f5561daef2 
Create Date: 2018-02-08 13:04:06.803068

"""

# revision identifiers, used by Alembic.
revision = 'a8e0d5299a86'
down_revision = '91f5561daef2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('current_status', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'current_status')
    ### end Alembic commands ###
