"""empty message

Revision ID: ad8c63f1135e
Revises: 2b54be9401bd
Create Date: 2018-11-19 09:30:39.961730

"""

# revision identifiers, used by Alembic.
revision = 'ad8c63f1135e'
down_revision = '2b54be9401bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('eppn', sa.String(length=128), nullable=True))
    # op.create_unique_constraint(op.f('uq_users_eppn'), 'users', ['eppn'])
    # op.drop_constraint(u'uq_users_email', 'users', type_='unique')
    # op.drop_column('users', 'email')
    op.alter_column('users', 'email', new_column_name='eppn')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('email', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # op.create_unique_constraint(u'uq_users_email', 'users', ['email'])
    # op.drop_constraint(op.f('uq_users_eppn'), 'users', type_='unique')
    # op.drop_column('users', 'eppn')
    op.alter_column('users', 'eppn', new_column_name='email')
    ### end Alembic commands ###
