"""add service_announcements table

Revision ID: c55e90324542
Revises: 2a55fb4059d4
Create Date: 2022-12-21 14:24:06.605557

"""

# revision identifiers, used by Alembic.
revision = 'c55e90324542'
down_revision = '2a55fb4059d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_announcements',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('targets', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_announcements'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_announcements')
    # ### end Alembic commands ###
