"""remove cost multipliers.

Revision ID: d09db0106be9
Revises: 7d8f697053e9
Create Date: 2016-11-14 15:12:37.972365

"""

# revision identifiers, used by Alembic.
revision = 'd09db0106be9'
down_revision = '7d8f697053e9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blueprints', 'maximum_lifetime')
    op.drop_column('blueprints', 'cost_multiplier')
    op.drop_column('blueprints', 'preallocated_credits')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blueprints', sa.Column('preallocated_credits', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('blueprints', sa.Column('cost_multiplier', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('blueprints', sa.Column('maximum_lifetime', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
