"""add alerts

Revision ID: da41c0a6e015
Revises: 594f5bd7bcf4
Create Date: 2021-09-13 12:54:36.310163

"""

# revision identifiers, used by Alembic.
revision = 'da41c0a6e015'
down_revision = '594f5bd7bcf4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('target', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('update_ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('target', 'source', name=op.f('pk_alerts'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    # ### end Alembic commands ###
