"""initial version

Revision ID: e1f66926f70c
Revises: None
Create Date: 2021-06-14 11:13:01.031003

"""

# revision identifiers, used by Alembic.
revision = 'e1f66926f70c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environment_templates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('environment_type', sa.String(length=128), nullable=True),
    sa.Column('base_config', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('allowed_attrs', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_environment_templates'))
    )
    op.create_table('locks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('acquired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locks'))
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('broadcasted', sa.DateTime(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ext_id', sa.String(length=128), nullable=True),
    sa.Column('email_id', sa.String(length=128), nullable=True),
    sa.Column('pseudonym', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('joining_date', sa.DateTime(), nullable=True),
    sa.Column('last_login_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('latest_seen_message_ts', sa.DateTime(), nullable=True),
    sa.Column('workspace_quota', sa.Integer(), nullable=True),
    sa.Column('tc_acceptance_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('ext_id', name=op.f('uq_users_ext_id')),
    sa.UniqueConstraint('pseudonym', name=op.f('uq_users_pseudonym'))
    )
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('pseudonym', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('join_code', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cluster', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('create_ts', sa.DateTime(), nullable=True),
    sa.Column('expiry_ts', sa.DateTime(), nullable=True),
    sa.Column('environment_quota', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces')),
    sa.UniqueConstraint('pseudonym', name=op.f('uq_workspaces_pseudonym'))
    )
    op.create_table('environments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template_id', sa.String(length=32), nullable=True),
    sa.Column('workspace_id', sa.String(length=32), nullable=True),
    sa.Column('labels', sa.Text(), nullable=True),
    sa.Column('maximum_lifetime', sa.Integer(), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('expiry_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['environment_templates.id'], name=op.f('fk_environments_template_id_environment_templates')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_environments_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_environments'))
    )
    op.create_table('workspace_user_associations',
    sa.Column('workspace_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('is_manager', sa.Boolean(), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workspace_user_associations_user_id_users')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_user_associations_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('workspace_id', 'user_id', name=op.f('pk_workspace_user_associations'))
    )
    op.create_table('instances',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('environment_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('provisioned_at', sa.DateTime(), nullable=True),
    sa.Column('deprovisioned_at', sa.DateTime(), nullable=True),
    sa.Column('errored', sa.Boolean(), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('to_be_deleted', sa.Boolean(), nullable=True),
    sa.Column('log_fetch_pending', sa.Boolean(), nullable=True),
    sa.Column('error_msg', sa.String(length=256), nullable=True),
    sa.Column('provisioning_config', sa.Text(), nullable=True),
    sa.Column('instance_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('fk_instances_environment_id_environments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_instances_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instances')),
    sa.UniqueConstraint('name', name=op.f('uq_instances_name'))
    )
    op.create_table('instance_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('instance_id', sa.String(length=32), nullable=True),
    sa.Column('log_level', sa.String(length=8), nullable=True),
    sa.Column('log_type', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_instance_logs_instance_id_instances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instance_logs'))
    )
    op.create_index(op.f('ix_instance_logs_instance_id'), 'instance_logs', ['instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instance_logs_instance_id'), table_name='instance_logs')
    op.drop_table('instance_logs')
    op.drop_table('instances')
    op.drop_table('workspace_user_associations')
    op.drop_table('environments')
    op.drop_table('workspaces')
    op.drop_table('users')
    op.drop_table('messages')
    op.drop_table('locks')
    op.drop_table('environment_templates')
    # ### end Alembic commands ###
