"""empty message

Revision ID: f092dbba3026
Revises: ad8c63f1135e
Create Date: 2018-11-20 13:01:18.328112

"""

# revision identifiers, used by Alembic.
revision = 'f092dbba3026'
down_revision = 'ad8c63f1135e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_id', sa.String(length=128), nullable=True))
    op.create_unique_constraint(op.f('uq_users_email_id'), 'users', ['email_id'])
    # end Alembic commands ###


def downgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_email_id'), 'users', type_='unique')
    op.drop_column('users', 'email_id')
    # end Alembic commands ###
