"""empty message

Revision ID: h6rg67898907
Revises: 37s5rj356547
Create Date: 2019-02-20 16:45:34.186981

"""

# revision identifiers, used by Alembic.
revision = 'h6rg67898907'
down_revision = '37s5rj356547'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('blueprint_quota', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'blueprint_quota')
    ### end Alembic commands ###
