"""empty message

Revision ID: he536vdwh29f
Revises: 9yuk6g899741
Create Date: 2019-07-18 11:50:00.78215

"""

# revision identifiers, used by Alembic.
revision = 'he536vdwh29f'
down_revision = '9yuk6g899741'

from alembic import op
import sqlalchemy as sa

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blueprints', sa.Column('gpu_enabled', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blueprints', 'gpu_enabled')
    ### end Alembic commands ###
