"""empty message

Revision ID: j4d9g3scvf4s
Revises: k8f2j557gt12
Create Date: 2019-03-13 13:17:34.1435233

"""

# revision identifiers, used by Alembic.
revision = 'j4d9g3scvf4s'
down_revision = 'k8f2j557gt12'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.add_column('blueprints', sa.Column('expiry_time', sa.DateTime(), nullable=True))
    # end Alembic commands ###


def downgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.drop_column('blueprints', 'expiry_time')
    # end Alembic commands ###
