"""empty message

Revision ID: k8f2j557gt12
Revises: f092dbba3026 
Create Date: 2018-02-07 14:07:34.165378

"""

# revision identifiers, used by Alembic.
revision = 'k8f2j557gt12'
down_revision = 'f092dbba3026'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('expiry_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'expiry_date')
    ### end Alembic commands ###
