FROM    ubuntu:14.04
MAINTAINER Olli Tourunen "olli.tourunen@csc.fi"

RUN apt-get update

# base requirements
RUN apt-get install -y openssh-server supervisor

# tools for admistration
RUN apt-get install -y tmux tree dstat lsof bash-completion time vim nano

# common packages for containers
RUN apt-get install -y git python python-pip python-dev python-virtualenv supervisor libffi-dev libssl-dev

RUN mkdir -p /var/run/sshd
RUN chmod 0755 /var/run/sshd

# Create and configure a user for ansible
RUN useradd --create-home -s /bin/bash ansible
ADD ansible-sudo /etc/sudoers.d/ansible
RUN mkdir -p /home/ansible/.ssh/
ADD id_rsa.pub /home/ansible/.ssh/authorized_keys
RUN chown -R ansible:ansible /home/ansible/ && chmod 700 /home/ansible/.ssh/ && chmod 600 /home/ansible/.ssh/authorized_keys
RUN usermod -p '*' ansible

EXPOSE 22

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
RUN mkdir -p /var/log/supervisor

CMD ["/usr/bin/supervisord"]
