---
- hosts:
    - docker_host
  sudo: True
  roles:
    - docker_host

- hosts:
    - docker_host
  sudo: True
  roles:
    - single_server_with_docker
  vars:
    - image_name: ubuntu_with_ssh

- hosts:
    - api
    - worker
    - frontend
  sudo: True
  roles:
      - cloud_user_with_sudo
      - common

- hosts: frontend
  sudo: True
  roles:
      - frontend

- hosts: api
  sudo: True
  roles:
      - api

- hosts: worker
  sudo: True
  roles:
      - worker

- hosts: sso
  sudo: True
  roles:
      - sso
      - cloud_user_with_sudo
